---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "build-bot.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    helm.sh/chart: {{ include "build-bot.chart" . }}
    app.kubernetes.io/name: {{ include "build-bot.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: datapio
secrets:
  - name: {{ .Values.secret }}
