---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "metacontroller.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    helm.sh/chart: {{ include "metacontroller.chart" . }}
    app.kubernetes.io/name: {{ include "metacontroller.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: datapio
