replicas:
  dashboard: 1
  pipelines_controller: 1
  pipelines_webhook: 1
  triggers_controller: 1
  triggers_webhook: 1

resources:
  pipelines_controller:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 500m
      memory: 256Mi

  pipelines_webhook:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 500m
      memory: 256Mi

  triggers_controller:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 500m
      memory: 256Mi

  triggers_webhook:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 500m
      memory: 256Mi

image:
  dashboard:
    name: gcr.io/tekton-releases/github.com/tektoncd/dashboard/cmd/dashboard@sha256
    tag: d6d1572aff2036707339fdcdf6a89e2850750a1ac643cd033ecdba4fbe4c3f20
    pullPolicy: IfNotPresent

  pipelines_controller:
    name: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/controller@sha256
    tag: 72a2bda21b5bc23550e94fdf7cee8a6e5bd82601f5d81a6237fc2b8c42321a59
    pullPolicy: IfNotPresent

  pipelines_webhook:
    name: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/webhook@sha256
    tag: 1d6336f2748cb8e5c19b17191a54c6adbbc77e2d1c60818f93282ec482bb2957
    pullPolicy: IfNotPresent

  triggers_controller:
    name: gcr.io/tekton-releases/github.com/tektoncd/triggers/cmd/controller@sha256
    tag: c04694411632b05b0bc2116c641432b8d596c5814394adbc659f16505fed9db4
    pullPolicy: IfNotPresent

  triggers_webhook:
    name: gcr.io/tekton-releases/github.com/tektoncd/triggers/cmd/webhook@sha256
    tag: c0f6cd59922c472bb3ad386513b681b8bf5aaf48e6811bd6de24bdf09062af8a
    pullPolicy: IfNotPresent

  kubeconfig_writer:
    name: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/kubeconfigwriter@sha256
    tag: 912d30334e63899f3875806b0633b5ddf3470d64fbd2333fc2c534afcfa9872d

  creds:
    name: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/creds-init@sha256
    tag: 8f8c43a115984e90db3b0cb3fcd46e1699ec15515ca7d258571a44c7d76040ca

  git:
    name: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init@sha256
    tag: 00466e8ec7d8a289140893523d33261ba5006dfb1bd9b96aee2736fc739dba5a

  nop:
    name: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/nop@sha256
    tag: b77955ba2711e1ba30ab48670bcafd725ddc01a105d173256e158053914dc42c

  bash:
    name: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/bash@sha256
    tag: a96b5840cdeb2a6598a8566a8607b925732286a8fdf15147be3591b7c7fb41f7

  gsutil:
    name: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/gsutil@sha256
    tag: 0130ec562b897c5929123d4e14cd3271cd58102f1f411f52cb6f415088bf5944

  entrypoint:
    name: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/entrypoint@sha256
    tag: 5c2a7261d923b8af29ad3be34a9c9a3abd1ed11a030ca1cc207293d203755ab4

  imagedigest_exporter:
    name: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/imagedigestexporter@sha256
    tag: 23e2de68c86de494aba98dabf02b175efc051827c52350bdd9a89f6a3d969ea9

  pr:
    name: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/pullrequest-init@sha256
    tag: 26a181a89c00ab840599508e905d1cfeed5db2b4ea41fbcc63c22979389e4a46

  build_gcs_fetcher:
    name: gcr.io/tekton-releases/github.com/tektoncd/pipeline/vendor/github.com/googlecloudplatform/cloud-builders/gcs-fetcher/cmd/gcs-fetcher@sha256
    tag: 5be2e14ed6b986198beca21a93af34e807586dcf9155babeca7f5971a2fa0311

  event_listener:
    name: gcr.io/tekton-releases/github.com/tektoncd/triggers/cmd/eventlistenersink@sha256
    tag: 34dc184a59d0c8e357b6208388cbbc9095a92508f522d18a3a371c22e0d4c930
