---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tekton.fullname" . }}-pipelines-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ include "tekton.chart" . }}
    app.kubernetes.io/name: {{ include "tekton.name" . }}-pipelines-webhook
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: datapio
spec:
  ports:
    - port: 443
      targetPort: 8443
  selector:
    app.kubernetes.io/name: {{ include "tekton.chart" . }}-pipelines-webhook
