---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "secret-injector.fullname" . }}
  labels:
    helm.sh/chart: {{ include "secret-injector.chart" . }}
    app.kubernetes.io/name: {{ include "secret-injector.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: datapio
  annotations:
    cert-manager.io/inject-ca-from-secret: "{{ .Release.Namespace }}/{{ include "secret-injector.servingCertificate" . }}"
webhooks:
  - name: {{ .Chart.name }}
    clientConfig:
      service:
        name: {{ include "secret-injector.fullname" . }}
        namespace: {{ .Release.Namespace }}
    rules:
      - operations:
          - CREATE
        apiGroups:
          - ""
          - apps
        apiVersions:
          - v1
        resources:
          - pods
          - deployments
    namespaceSelector:
      matchLabels:
        app.datap.io/kind: Project
